baseURL = 'https://cannot.la/'
languageCode = 'en-us'
title = 'Cannot Lah'
theme = 'magick'
enableGitInfo = true
ignoreFiles = ['content/images/.*\.md$']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true